// ./localization.js
const translations = {
    en : {
        expenses: "Expenses",
        report : "Report",
        new : "New",
        settings: "Settings",
        categories: "Categories",
        enter_new_categories: "enter a new category",
        add_category : "ADD CATEGORY",
        select_language_and_currency : "Select Language and Currency:",
        german: "German",
        english: "English",
        sure_delete: "Are you sure you want to delete?",
        delete_all: "Delete All Data",
        delete_cat: 'Delete unused Categories',
        total_amount: 'Total Amount',
        name: "Name",
        amount: "Amount",
        date: "Date",
        category: "Category",
        cancel: "cancel",
        delete: "delete",
        amount_per_date: "Amount per Day",
        select_category: "Select a Category",
        select_frequency: "Select a Frequency",
        enter_date: "Enter a Date",
        enter_name: "enter a name",
        enter_amount: "enter the amount",
        enter_description: "enter a description",
        submit: "SUBMIT",
        invalid_date_format: "Invalid Date Format!",
        unique: "one-time",
        daily: "daily",
        weekly: "weekly",
        monthly: "monthly",
        yearly: "yearly"
    },

    de :{
        expenses: "Ausgaben",
        report : "Berichte",
        new : "Neu",
        settings: "Einstellungen",
        categories: "Kategorien",
        enter_new_categories : "gib eine neue Kategorie ein",
        add_category : " KATEGORIE HINZUFÜGEN",
        select_language_and_currency : "Wähle Sprache und Währung:",
        german: "Deutsch",
        english: "Englisch",
        sure_delete: "Daten wirklich löschen?",
        delete_all: "Alle Daten löschen",
        delete_cat: 'Unbenutzte Kategorien löschen',
        total_amount: 'Gesamtsumme',
        name: "Name",
        amount: "Betrag",
        date: "Datum",
        category: "Kategorie",
        cancel: "abbrechen",
        delete: "löschen",
        amount_per_date: "Betrag pro Tag",
        select_category: "Wähle eine Kategorie",
        select_frequency: "Wähle eine Frequenz",
        enter_date: "Gib ein Datum ein",
        enter_name: "gib einen Namen ein",
        enter_amount: "gib einen Betrag ein",
        enter_description: "gib eine Beschreibung ein",
        submit: "SENDEN",
        invalid_date_format: "Ungültiges Format!",
        unique: "einmalig",
        daily: "täglich",
        weekly: "wöchentlich",
        monthly: "monatlich",
        yearly: "jährlich"
    }

}
export { translations };