// ./localization.js
const translations = {
    en : {
        expenses: "Expenses",
        report : "Report",
        new : "Add Expense",
        settings: "Settings",
        categories: "Categories",
        enter_new_categories: "enter a new category",
        add_category : "ADD CATEGORY",
        select_language: "Select Language ",
        and_currency : " and Currency ",
        german: "German",
        english: "English",
        sure_delete: "Are you sure you want to delete?",
        delete_all: "Delete All Data",
        delete_cat: 'Delete unused Categories',
        total_amount: 'Total Amount',
        name: "Name",
        amount: "Amount",
        date: "Date",
        category: "Category",
        cancel: "cancel",
        delete: "delete",
        amount_per_date: "Amount per Day",
        amount_per_week: "Amount per Week",
        amount_per_month: "Amount per Month",
        amount_per_year: "Amount per Year",
        select_category: "Select a Category",
        select_frequency: "Select a Frequency",
        enter_date: "Enter a Date",
        enter_name: "enter a name",
        enter_amount: "enter the amount",
        enter_description: "enter a description",
        submit: "SUBMIT",
        invalid_date_format: "Invalid Date Format!",
        unique: "one-time",
        daily: "daily",
        weekly: "weekly",
        monthly: "monthly",
        yearly: "yearly",
        KW: "CW",
        success: "success",
        success_note: "Item added to the list successfully.",
        missing_field: "Please fill in all fields before submitting.",
        pie_chart: "Show Donat",
        bar_chart: "Show Histogram"
    },

    de :{
        expenses: "Ausgaben",
        report : "Berichte",
        new : "Ausgabe hinzufügen",
        settings: "Einstellungen",
        categories: "Kategorien",
        enter_new_categories : "gib eine neue Kategorie ein",
        add_category : " KATEGORIE HINZUFÜGEN",
        select_language : "Wähle Sprache ",
        and_currency : " und Währung ",
        german: "Deutsch",
        english: "Englisch",
        sure_delete: "Daten wirklich löschen?",
        delete_all: "Alle Daten löschen",
        delete_cat: 'Unbenutzte Kategorien löschen',
        total_amount: 'Gesamtsumme',
        name: "Name",
        amount: "Betrag",
        date: "Datum",
        category: "Kategorie",
        cancel: "abbrechen",
        delete: "löschen",
        amount_per_date: "Betrag pro Tag",
        amount_per_week: "Betrag pro Woche",
        amount_per_month: "Betrag pro Monat",
        amount_per_year: "Betrag pro Jahr",
        select_category: "Wähle eine Kategorie",
        select_frequency: "Wähle eine Frequenz",
        enter_date: "Gib ein Datum ein",
        enter_name: "gib einen Namen ein",
        enter_amount: "gib einen Betrag ein",
        enter_description: "gib eine Beschreibung ein",
        submit: "SENDEN",
        invalid_date_format: "Ungültiges Format!",
        unique: "einmalig",
        daily: "täglich",
        weekly: "wöchentlich",
        monthly: "monatlich",
        yearly: "jährlich",
        KW: "KW",
        success: "Erfolg!",
        success_note: "Ausgabe erfolgreich hinzugefügt!",
        missing_field: "Bitte fülle das fehlende Feld aus!",
        pie_chart: "Zeige Kuchendiagramm",
        bar_chart: "Zeige Histogramm"
    }

}
export { translations };